# Generated by Django 6.0.2 on 2026-05-11 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('part_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=60)),
                ('sta', models.CharField(max_length=4)),
                ('bl', models.CharField(max_length=4)),
                ('wl', models.CharField(max_length=5)),
                ('dwg', models.CharField(max_length=20)),
                ('sht', models.CharField(max_length=4)),
                ('rev', models.CharField(max_length=3)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('TORQUE', 'TORQUE'), ('SEAL', 'SEAL'), ('BOND', 'BOND'), ('HIRF', 'HIRF'), ('FINISH', 'FINISH'), ('RETEST', 'RETEST'), ('DCMA', 'DCMA'), ('OTHER', 'OTHER')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.part')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, help_text='User-entered job number to help planning identify the job.', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parts', models.ManyToManyField(to='core.part')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.part')),
                ('planning_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.planningrequest')),
            ],
        ),
    ]
